# https://hydra.cc/docs/configure_hydra/intro/

# enable color logging
defaults:
  # enable color logging
  - override hydra_logging: colorlog
  - override job_logging: custom

# output directory, generated dynamically on each run
run:
  dir: ${paths.task_dir}/${run_name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
sweep:
  dir: ${paths.task_dir}/multiruns/${now:%Y-%m-%d}_${now:%H-%M-%S}
  subdir: ${hydra.job.num}