name: 'ncsnpp'
scale_by_sigma: False
normalization: 'GroupNorm'
nonlinearity: 'swish'
nf: 4
ch_mult: [1, 2]
num_res_blocks: 2
attn_resolutions: [32, ]
resamp_with_conv: True
conditional: True
fir: False
fir_kernel: [1, 3, 3, 1]
skip_rescale: True
resblock_type: 'biggan'
progressive: 'none'
progressive_input: 'none'
progressive_combine: 'sum'
attention_type: 'ddpm'
init_scale: 0.
# embedding_type: 'positional'
embedding_type: 'fourier'
fourier_scale: 16
conv_size: 3
dropout: 0.1
data_init: False
trainable_embedding: False