# path to root directory
# this requires PROJECT_ROOT environment variable to exist
# PROJECT_ROOT is inferred and set by pyrootutils package in `train.py` and `eval.py`
root_dir: ${oc.env:PROJECT_ROOT}

# path to working directory
work_dir: ${hydra:runtime.cwd}

# path to outs directory
root_out_dir: ${paths.root_dir}/outs

# path to data directory
data_dir: ${paths.root_dir}/~/

exp_dir: ${paths.root_out_dir}/${name}
task_dir: ${paths.root_out_dir}/${name}/${task_name}


# path to runtime output directory, created dynamically by hydra
# path generation pattern is specified in `configs/hydra/default.yaml`
# use it to store all files generated during the run, like ckpts and metrics
output_dir: ${hydra:runtime.output_dir}