# @package _global_

# specify here default training configuration
defaults:
  - _self_
  - main/dataset: mnist.yaml
  - main/loss: default
  - main/model: cifarnet.yaml
  - main/sde: subvp.yaml
  - main/training: null
  - mode: default.yaml
  # - callbacks: null
  # - logger: null # set logger here or use command line (e.g. `python run.py logger=wandb`)


  - experiment: null
  - hparams_search: null

  # optional local config
  - optional local: default.yaml

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: custom
  

  # Disable changing current working dir to job's output dir
  # - override hydra/job/chdir: False

# path to original working directory
# hydra hijacks working directory by changing it to the current log directory,
# so it's useful to have this path as a special variable
# https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
cwd: ${hydra:runtime.cwd}
rwd: ${hydra:runtime.output_dir}

# path to folder with data
data_dir: ${work_dir}/data/

# pretty print config at the start of the run using Rich library
print_config: True

# disable python warnings if they annoy you
ignore_warnings: True

# evaluate on test set, using best model weights achieved during training
# lightning chooses best weights based on metric specified in checkpoint callback
test_after_training: True

# seed for random number generators in pytorch, numpy and python.random
seed: null

# name of the run is accessed by loggers
# should be used along with experiment mode
name: null

# model_path: null

only_test: False