# @package _global_

# runs 1 train, 1 validation and 1 test step

defaults:
  - default.yaml

# sets level of all command line loggers to 'DEBUG'
# https://hydra.cc/docs/tutorials/basic/running_your_app/logging/
hydra:
  job_logging:
    root:
      level: INFO